### ISSUE TITLE
Implementación de BasicBodyBuilder

### ISSUE THREAD

**Issue by LuisEgui** [Missionpage/PhysicsSimulator#9]
Se tiene que:

- Implementar la clase **BasicBodyBuilder** según el archivo UML: \resources\uml\factories
- Implementar **BasicBodyBuilderTest** en: \test\java\simulator\factories utilizando _JUnit_

**Comment by Missionpage** [comment]
Se necesita aclaración sobre el método `JSONObject getBuilderInfo()`. Queda pendiente para implementar.

**Comment by LuisEgui** [comment]
Falta implementar el método `JSONObject createData()`.
